version: "3"
services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: app
        env_file: .env
        ports: 
            - "$PORT:$PORT"